server:
  port: 1993

spring:
  jackson:
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
    username: root
    password: 12345678
thread-pool:
  core-size: 32
  max-size: 64
  keep-alive: 60
  allow-core-thread-timeout: true
  queue-capacity: 100
  times: 5

huobi:
  arbitrage:
#    rest-host: https://api-aws.huobi.pro
    rest-host: https://api.huobi.pro
    webSocketHost: wss://api.huobi.pro
#    webSocketHost: wss://api-aws.huobi.pro
    starId: 0
    endId: 135
    webSocketAutoConnect: true
    apiKey: nicai
    secretKey: nicai
    sportAccountId: nicai
    scale: 3
    jobTime: 1500